THEMES = {
    "light": {
        "bg":           "#f5f5f5",
        "top_bar":      "#2c3e50",
        "top_fg":       "white",
        "frame_bg":     "#f5f5f5",
        "entry_bg":     "white",
        "entry_fg":     "black",
        "tree_bg":      "white",
        "tree_fg":      "black",
        "tree_select":  "#cce5ff",
        "label_fg":     "#333333",
        "btn_bg":       "#e0e0e0",
        "overdue_fg":   "#cc0000",
        "today_fg":     "#cc6600",
        "done_fg":      "#888888",
        "high_fg":      "#cc0000",
        "medium_fg":    "#cc6600",
        "low_fg":       "#2e7d32",
    },
    "dark": {
        "bg":           "#1e1e1e",
        "top_bar":      "#111111",
        "top_fg":       "white",
        "frame_bg":     "#1e1e1e",
        "entry_bg":     "#2d2d2d",
        "entry_fg":     "white",
        "tree_bg":      "#2d2d2d",
        "tree_fg":      "#e0e0e0",
        "tree_select":  "#3a3a5c",
        "label_fg":     "#cccccc",
        "btn_bg":       "#3a3a3a",
        "overdue_fg":   "#ff6b6b",
        "today_fg":     "#ffa94d",
        "done_fg":      "#666666",
        "high_fg":      "#ff6b6b",
        "medium_fg":    "#ffa94d",
        "low_fg":       "#69db7c",
    }
}